[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
lisk_mainnet = "https://mainnet-service.lisk.com/rpc" # Replace with actual URL
lisk_testnet = "https://testnet-service.lisk.com/rpc" # Replace with actual URL

[etherscan]
lisk = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer-api.lisk.com/api" } # Update this too if needed